---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "check-digit.fullname" . }}
  labels:
    app: {{ template "check-digit.name" . }}
    chart: {{ template "check-digit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "check-digit.name" . }}
    release: {{ .Release.Name }}


---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ include "check-digit.fullname" . }}-ambassador
  name: {{ include "check-digit.fullname" . }}-ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: check_digit_mapping
      ambassador_id: ambassador-default-1
      prefix: /v2/public/uli/
      rewrite: /uli/
      service: {{ template "check-digit.fullname" .}}:{{ .Values.service.port }}
      timeout_ms: 60000
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "check-digit.fullname" . }}-grpc
  labels:
    app: {{ template "check-digit.fullname" . }}
    chart: {{ template "check-digit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.grpc.type }}
  ports:
    - port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.grpc.name }}
  selector:
    app: {{ template "check-digit.name" . }}
    release: {{ .Release.Name }}

