apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "email-service.fullname" . }}
  annotations:
    downscaler/uptime: Mon-Fri 10:00-23:00 UTC
  labels:
    app: {{ include "email-service.name" . }}
    chart: {{ include "email-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "email-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "email-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/New_York
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: "4"
              memory: "2200Mi"
          env:
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: inst-postgres-credentials
                  key: url
            - name: KAFKA_CLUSTER_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: kafka.hosts
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-email-credentials
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-email-credentials
                  key: aws-secret-access-key
            - name: AWS_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: s3-configmap
                  key: aws-environment
            - name: BANK_FILTER_LIST
              valueFrom:
                configMapKeyRef:
                  name: bank-filter-configmap
                  key: bank-filter-list
            - name: HTTP_CENSUS_PORT
              valueFrom:
                configMapKeyRef:
                  name: http-configmap
                  key: census.port
            - name: EMAIL_LOG_LEVEL
              value: INFO
            - name: KAFKA_EMAIL_TOPIC
              value: {{.Values.kafka.emailTopic}}
            - name: KAFKA_EMAIL_CONSUMER_GROUP_ID
              value: {{.Values.kafka.emailGroup}}
            - name: EMAIL_SUBJECT
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: emailSubject
            - name: EMAIL_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: emailContent
            - name: SENDER_EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: emailSender
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
