# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  # third cron
  - name: newmen-tests
    image:
      repository: patrickhshi/newman-dev
      tag: test
      imagePullPolicy: Always
    # optional env vars
    env:
    - name: HOST_FILING
      value:
    - name: HOST_ADMIN
      value:
    - name: HOST_PUBLIC
      value:
    - name: USERNAME_NM
      value:
    - name: PASSWORD_NM
      value:
    schedule: "*/2 * * * *"
    command: ["/bin/sh"]
    args:
      -  "-c"
      - authToken=$(./scripts/authTokenGen.sh $USERNAME_NM $PASSWORD_NM) && ./node_modules/.bin/newman run hmda-filing/hmda-filing-api-test.json -d hmda-filing/hmda-filing-api-config.json --env-var host_filing=$HOST_FILING --env-var host_admin_api=$HOST_ADMIN --env-var host_public=$HOST_PUBLIC --env-var authToken="Bearer $authToken"
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never