---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configmap
data:
  cassandra-hosts: {{ .Values.cassandra.hosts }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
data:
  auth.url: {{ .Values.keycloak.url }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
data:
  kafka.hosts: {{ .Values.kafka.hosts }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-configmap
data:
  check.digit.host: {{ .Values.grpc.check_digit.host }}
  check.digit.port: "{{ .Values.grpc.check_digit.port }}"
  census.host: {{ .Values.grpc.census.host }}
  census.port: "{{ .Values.grpc.census.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: http-configmap
data:
  check.digit.host: {{ .Values.http.check_digit.host }}
  check.digit.port: "{{ .Values.http.check_digit.port }}"
  census.host: {{ .Values.http.census.host }}
  census.port: "{{ .Values.http.census.port }}"
