apiVersion: v1
kind: Service
metadata:
  name: {{ template "institutions-api.fullname" . }}
  labels:
    app: {{ template "institutions-api.name" . }}
    chart: {{ template "institutions-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "institutions-api.name" . }}
    release: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.ambassador.name }}
  name: {{ .Values.ambassador.name }}
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind: Mapping
      name: institution_api_mapping
      method: GET
      prefix: /v2/public/institutions/
      rewrite: /institutions/
      service: {{ template "institutions-api.fullname" .}}:{{ .Values.service.port }}
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: institution_api_search_mapping
      method: GET
      prefix: /v2/public/institutions?
      rewrite: /institutions?
      service: {{ template "institutions-api.fullname" .}}:{{ .Values.service.port }}
spec:
  type: {{ .Values.ambassador.service.type }}
  ports:
  - name: {{ .Values.ambassador.name }}
    port: {{ .Values.ambassador.port }}
    targetPort: {{ .Values.ambassador.port }}
  selector:
service: {{ .Values.ambassador.name }}
