---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-modifiedlar-config"
data:
  aws-environment: "{{ .Values.aws.environment }}"
  s3-private-bucket: "{{ .Values.aws.s3privatebucket }}"
  s3-public-bucket: "{{ .Values.aws.s3publicbucket }}"
  aws-region: "{{ .Values.aws.region }}"
  postgres.ssl: "{{ .Values.postgresql.ssl }}"
  postgres.user:  "{{ .Values.postgresql.postgresUser }}"
  postgres.database: "{{ .Values.postgresql.postgresDatabase }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modified-lar-http-configmap
data:
  census.host: {{ .Values.http.census.host }}
  census.port: "{{ .Values.http.census.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-filter-configmap
data:
  bank-filter-list: "{{ .Values.filter.bankfilterlist }}"