---
apiVersion: v1
kind: ConfigMap
metadata:
  name: irs-http-configmap
data:
  census.host: {{ .Values.http.census.host }}
  census.port: "{{ .Values.http.census.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-filter-configmap
data:
  bank-filter-list: "{{ .Values.filter.bankfilterlist }}"
